name: Node.js Package with Yarn

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - run: yarn build
      - run: |
          cp package.json lib/
          cp LICENSE lib/
          cp README.md lib/
      - run: |
          cd lib
          yarn pack --filename react-components.tgz
          yarn publish react-components.tgz
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}